---
title: "Geo_coding"
author: "ClareCallahan"
date: "4/23/2021"
output: html_document
---


#Data from: https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/export/ 
Process needed to create 2D for 'state' to be incorporated into GLM with poly option 
```{r setup, include=FALSE}

loadlibs = function(libs) {
  for(lib in libs) {
    class(lib)
    if(!do.call(require,as.list(lib))) {install.packages(lib)}
    do.call(require,as.list(lib))
  }
}
libs = c("tidyverse","data.table")
loadlibs(libs)
```

```{r}

setwd("~/GitHub/Covid-19-Closure-Impact/Data")

geo<- read.csv('us-zip-code-latitude-and-longitude.csv', header= FALSE, stringsAsFactors = FALSE)

geo<- as.data.frame(geo)

geo<-geo%>% separate(V1, into=c("Zip", "City", "State", "Latitude","Longitude","Timezone","Daylight_savings", "geopoint"), sep=";" )

geo<- geo[-1,]

geo$Latitude<-as.numeric(geo$Latitude)
geo$Longitude<-as.numeric(geo$Longitude)



```


```{r}
state_latLong <- geo%>%
  group_by(geo$State)%>%
  summarise(Latitude = mean(Latitude, na.rm = TRUE),
            Longitude = mean(Longitude, na.rm = TRUE))


```